apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-pstgr-fixed
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: manual